name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when you push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub's virtual environment (Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use Node.js version 18 (or a version compatible with your project)

      - name: Install dependencies
        run: npm install # Install your project's npm dependencies

      - name: Fix react-scripts permissions # NEW STEP ADDED
        run: chmod +x node_modules/.bin/react-scripts # Give execute permission to react-scripts

      - name: Build React App
        run: npm run build # Build your React application for production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action to deploy to gh-pages branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
          publish_dir: ./build # The directory containing your built React app
          # You can specify a custom branch if not 'gh-pages'
          # publish_branch: gh-pages
